In [1]:
import numpy as np

In [2]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [3]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
#어레이 덧셈
array1+2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
#어레이 뺄셈
array1-2

array([-2,  0,  2,  4,  6,  8, 10, 12, 14, 16])

In [5]:
array1*2  
#array1의 2배 값

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
array1/2 
#array1의 나눗셈

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [13]:
#array1의 제곱
array1**2

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324], dtype=int32)

In [14]:
array1  #사칙연산을 한다고 원본값이 변하는 것은 아니다.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
#변환된 값 저장하기
array1 = array1*2

In [9]:
array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [24]:
#어레이 끼리의 덧셈
array1+array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [18]:
#어레이 끼리의 뺄셈
array1-array2

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [19]:
#어레이 끼리의 곱셈
array1*array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [20]:
#어레이 끼리의 나눗셈
array1/array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [25]:
b = np.array([[0,1,2],[3,4,5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [27]:
#3중 리스트로부터 3차원 배열 만들기
c = np.array([[[0,1,2],[3,4,5]],[[5,4,3],[2,1,0]]])
print(c)

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]


In [28]:
d = np.zeros(8) #0이 8개 저장된 배열
print(d)

e = np.ones(8) #1이 8번 저장된 배열
print(e)

f = np.arange(8) #0부터 7까지 저장된 배열
print(f)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7]


In [30]:
a = np.array([[0,1,2],
              [3,4,5]]) # 2x3(2행 3열)의 2차원 배열

print(np.shape(a))  #a의 형태를 표시

(2, 3)


In [34]:
print(len(a)) # a가 몇 행으로 이루어져 있는지 확인

2


In [33]:
a = np.array([[0,1,2],
              [3,4,5]]) # 2x3(2행 3열)의 2차원 배열

print(a)
print()
print(a+3) # 각 요소에 +3을 한다.
print()
print(a*3) # 각 요소에 *3을 한다.

[[0 1 2]
 [3 4 5]]

[[3 4 5]
 [6 7 8]]

[[ 0  3  6]
 [ 9 12 15]]


In [35]:
# 배열끼리의 연산
b = np.array([[0,1,2],
              [3,4,5]])  #2x3의 2차원 배열
c = np.array([[2,0,1],
              [5,3,4]])  #2x3의 2차원 배열

print(b)
print()
print(c)
print()
print(b+c)   # 같은 행 끼리만 연산된다.
print()
print(b*c)   # 같은 행 끼리만 연산된다.

[[0 1 2]
 [3 4 5]]

[[2 0 1]
 [5 3 4]]

[[2 1 3]
 [8 7 9]]

[[ 0  0  2]
 [15 12 20]]


In [36]:
a = ([1,2,3,4,5])
print(a[3])

4


In [37]:
a[2] = 9
print(a)

[1, 2, 9, 4, 5]


In [38]:
b = np.array([[0,1,2],
             [3,4,5]])

print(b[1,2])  #b[1][2]와 같다.

5


In [39]:
b[1,2] = 9
print(b)

[[0 1 2]
 [3 4 9]]


In [41]:
c = np.array([[0,1,2],
             [3,4,5]])
print(c[1,:])  #인덱스가 1인 행을 취득 c[행, 열]
print()
c[:,1] = np.array([6,7]) #인덱스가 1인 열을 교체 c[행, 열]
print(c)

[3 4 5]

[[0 6 2]
 [3 7 5]]


In [44]:
a = np.array([[0,1,2],
             [3,4,5]])  #2차원 배열

print('합계:', np.sum(a))
print('평균:', np.average(a))
print('최댓값:', np.max(a))
print('최솟값:', np.min(a))

합계: 15
평균: 2.5
최댓값: 5
최솟값: 0


In [49]:
a = np.array([[0,1,2],
             [3,4,5]])
b = np.array([[5,4,3],
             [2,1,0]])

print('덧셈: \n', a+b)
print('뺄셈: \n', a-b)
print('곱셈: \n', a*b)

덧셈: 
 [[5 5 5]
 [5 5 5]]
뺄셈: 
 [[-5 -3 -1]
 [ 1  3  5]]
곱셈: 
 [[0 4 6]
 [6 4 0]]
