In [1]:
import numpy as np

In [2]:
array1 = np.array([2,3,5,7,11,13,15,17,19,23])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 15, 17, 19, 23])

In [4]:
array1[0] 
#0번째 인덱스값 불러오기

2

In [5]:
array1[5]

13

In [6]:
array1[-1]

23

In [7]:
array1[[1,3,4]]  
#리스트 안에 리스트 넣어서 인덱스값 불러오기

array([ 3,  7, 11])

In [8]:
array2 = np.array([2,1,3])

In [12]:
array1[array2]  
#다른 어레이로 인덱싱 하기

array([5, 3, 7])

In [13]:
array1[2:7]

array([ 5,  7, 11, 13, 15])

In [14]:
array1[2:6:3] 
#2번부터 6번 인덱스까지 숫자 세개씩 건너뛰며 불러오기

array([ 5, 13])