In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3], [-1,0,2], [3,4,5], [2,-2,-3]])
B = np.array([[0,2], [1,-1],[3,-4]])

In [3]:
A

array([[ 1,  2,  3],
       [-1,  0,  2],
       [ 3,  4,  5],
       [ 2, -2, -3]])

In [4]:
B

array([[ 0,  2],
       [ 1, -1],
       [ 3, -4]])

In [5]:
A[1][1]

0

In [6]:
B[2][0]

3

In [10]:
array1 = np.full(6, 7)
print(array1)

[7 7 7 7 7 7]


In [11]:
C= np.array([[1,2,-1],[1,1,-3]])
D = np.array([[3,2,-2],[-1,2,1]])

In [12]:
C + D

array([[ 4,  4, -3],
       [ 0,  3, -2]])

In [13]:
C= np.array([[1,2,-1],[1,1,-3]])
E = np.array([[3],[1],[2]])

In [26]:
print(np.dot(C, E))
C = np.asmatrix(C)
E = np.asmatrix(E)

[[ 3]
 [-2]]


In [23]:
C*E

matrix([[ 3],
        [-2]])

In [17]:
F = np.array([[3,2], [1,1], [2,-1]])

In [28]:
print(np.dot(C, F))
print()
F = np.asmatrix(F)
print(F)

[[ 3  5]
 [-2  6]]

[[ 3  2]
 [ 1  1]
 [ 2 -1]]


In [25]:
C*F

matrix([[ 3,  5],
        [-2,  6]])