In [2]:
import numpy

In [3]:
array1 = numpy.array([2,3,5,7,11,13,17,19])

In [4]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19])

In [5]:
type(array1)
#numpy.ndarray  n차원의 어레이다.

numpy.ndarray

In [6]:
array1.shape
#(8,) 8개의 요소가 들어있다.

(8,)

In [8]:
array2 = numpy.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [9]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
type(array2)

numpy.ndarray

In [11]:
array2.shape

(3, 4)

In [12]:
array1.size

8

In [29]:
import numpy as np
import random

array1 = np.full(6,0)
array2 = np.random.random(6)

In [30]:
array1

array([0, 0, 0, 0, 0, 0])

In [26]:
array2

array([0.94928142, 0.65932815, 0.12024949, 0.12671646, 0.48548106,
       0.63303343])