In [1]:
import numpy as np

In [2]:
#행렬의 곱_곱셈을 하기 전에 앞의 행과 뒤의 열의 갯수가 같은지 확인
a = np.array([[0,1,2],
             [1,2,3]])
b = np.array([[2,1],
             [2,1],
            [2,1]])
print(np.dot(a,b))

[[ 6  3]
 [12  6]]


In [3]:
a = np.array([[0,1,2],
             [3,4,5],
             [6,7,8]])
b = np.array([[0,1,2],
             [2,0,1],
             [0,2,0]])
print(np.dot(a, b))

[[ 2  4  1]
 [ 8 13 10]
 [14 22 19]]


In [4]:
#행렬의 곱
c = np.array([[0,1,2],
             [3,4,5],
             [6,7,8]])
d = np.array([[0,2,0],
             [2,0,2],
             [0,2,0]])
print(np.dot(c,d))

[[ 2  4  2]
 [ 8 16  8]
 [14 28 14]]
